const express = require('express');
const router = express.Router();
const bookingController = require('../controllers/bookingController');
const auth = require('../middleware/auth'); 
const upload = require('../middleware/upload'); 
router.get('/booked-slots', bookingController.getBookedSlots);
router.post('/', auth, upload.single('payment_proof'), bookingController.createBooking);
router.get('/my-bookings', auth, bookingController.getUserBookings);
router.get('/admin/notifications', auth, bookingController.getNotificationCount);
router.get('/admin/all', auth, bookingController.getAllBookings);
router.delete('/:id', auth, bookingController.cancelBooking);
router.put('/:id', auth, bookingController.updateBookingStatus);
module.exports = router;